/**
 * @module src/redux/constants/index.js
 * @fileoverview The main `Redux` action types module.
 * @imports YARN:react
 * @imports YARN:react-redux::{createStore}
 * @exports {Object} New store object
 */

// API INVOCATION ACTION TYPE
// (Specifically used to trigger the API middleware action.)
export const API_MIDDLEWARE_INVOKE = 'API_MIDDLEWARE_INVOKE';


export const API_MIDDLEWARE_USERS_ENDPOINT = 'users';
export const API_MIDDLEWARE_SENTENCE_ENDPOINT = 'sentence';
export const API_MIDDLEWARE_RULES_ENDPOINT = 'rules';
export const API_MIDDLEWARE_PEOPLE_REVIEWS_ENDPOINT = 'review';
export const API_MIDDLEWARE_SENTENCE_RULES_ENDPOINT = 'sentenceRule';
export const API_MIDDLEWARE_SEARCH_ENDPOINT = 'search';
export const API_MIDDLEWARE_RETRAIN_ENDPOINT = 'retrain';
export const API_MIDDLEWARE_REVIEWER_ENDPOINT = 'reviewer';
export const API_MIDDLEWARE_THREADS_ENDPOINT = 'threads';

export const GET_SENTENCE_REQUEST = 'GET_SENTENCE_REQUEST';
export const GET_SENTENCE_SUCCESS = 'GET_SENTENCE_SUCCESS';
export const GET_SENTENCE_FAILURE = 'GET_SENTENCE_FAILURE';

export const GET_RULES_REQUEST = 'GET_RULES_REQUEST';
export const GET_RULES_SUCCESS = 'GET_RULES_SUCCESS';
export const GET_RULES_FAILURE = 'GET_RULES_FAILURE';

export const POST_REVIEW_REQUEST = 'POST_REVIEW_REQUEST';
export const POST_REVIEW_SUCCESS = 'POST_REVIEW_SUCCESS';
export const POST_REVIEW_FAILURE = 'POST_REVIEW_FAILURE';

export const GET_RULE_REVIEW_REQUEST = 'GET_RULE_REVIEW_REQUEST';
export const GET_RULE_REVIEW_SUCCESS = 'GET_RULE_REVIEW_SUCCESS';
export const GET_RULE_REVIEW_FAILURE = 'GET_RULE_REVIEW_FAILURE';

export const GET_REVIEWER_REQUEST = 'GET_REVIEWER_REQUEST';
export const GET_REVIEWER_SUCCESS = 'GET_REVIEWER_SUCCESS';
export const GET_REVIEWER_FAILURE = 'GET_REVIEWER_FAILURE';

export const GET_SENTENCE_TO_REVIEW_REQUEST = 'GET_SENTENCE_TO_REVIEW_REQUEST';
export const GET_SENTENCE_TO_REVIEW_SUCCESS = 'GET_SENTENCE_TO_REVIEW_SUCCESS';
export const GET_SENTENCE_TO_REVIEW_FAILURE = 'GET_SENTENCE_TO_REVIEW_FAILURE';

export const GET_LEADERBOARD_REQUEST = 'GET_LEADERBOARD_REQUEST';
export const GET_LEADERBOARD_SUCCESS = 'GET_LEADERBOARD_SUCCESS';
export const GET_LEADERBOARD_FAILURE = 'GET_LEADERBOARD_FAILURE';

export const SUBMIT_REVIEW_REQUEST = 'SUBMIT_REVIEW_REQUEST';
export const SUBMIT_REVIEW_SUCCESS = 'SUBMIT_REVIEW_SUCCESS';
export const SUBMIT_REVIEW_FAILURE = 'SUBMIT_REVIEW_FAILURE';

export const RESET_REVIEWER = 'RESET_REVIEWER';

export const NO_SENTENCES = 'NO_SENTENCES';

export const POST_REVIEWER_REQUEST = 'POST_REVIEWER_REQUEST';
export const POST_REVIEWER_SUCCESS = 'POST_REVIEWER_SUCCESS';
export const POST_REVIEWER_FAILURE = 'POST_REVIEWER_FAILURE';

export const GET_THREADS_REQUEST = 'GET_THREADS_REQUEST';
export const GET_THREADS_SUCCESS = 'GET_THREADS_SUCCESS';
export const GET_THREADS_FAILURE = 'GET_THREADS_FAILURE';

export const POST_DATASET_REQUEST = 'POST_DATASET_REQUEST';
export const POST_DATASET_SUCCESS = 'POST_DATASET_SUCCESS';
export const POST_DATASET_FAILURE = 'POST_DATASET_FAILURE';

export const POST_RETRAIN_REQUEST = 'POST_RETRAIN_REQUEST';
export const POST_RETRAIN_SUCCESS = 'POST_RETRAIN_SUCCESS';
export const POST_RETRAIN_FAILURE = 'POST_RETRAIN_FAILURE';

// STOP SPINNER ACTION
export const DONE_GETTING_THREADS = 'DONE_GETTING_THREADS';
export const DONE_GETTING_REVIEWER = 'DONE_GETTING_REVIEWER';
export const DONE_GETTING_SENTENCE = 'DONE_GETTING_SENTENCE';
export const DONE_GETTING_RULES = 'DONE_GETTING_RULES';
export const DONE_GETTING_RULE_REVIEW = 'DONE_GETTING_RULE_REVIEW';
